(**
 * Autogenerated metadata about the grammar.
 *
 * {b See:} [Converter] for a description of the format of the grammar file.
 *)

(**
 * [action_table.(curr_state).(lookahead)] is the action that should be taken
 * by the parser when it is in [curr_state] with a lookahead symbol of
 * [lookahead].
 *)
val action_table : Lr_action.t array array

(**
 * [token_to_var_id t] is the variable id that corresponds to [t].
 *)
val token_to_var_id : Token.t -> int
