(**
 * Autogenerated metadata about the grammar.
 *
 * {b See:} Converter for a description of the format of the grammar file.
 *)

val action_table : Lr_action.t array array

val production_length : int array array
