(** Converts from a Token array to a Parse Tree *)

(**
 * [parse arr] parses [arr] based off the autogenerated [Grammar] metadata
 * and is the resulting parse tree .
 *
 * Note that any unit productions in the grammar are squashed so the final
 * parse tree contains no nodes of the form:
 * - [Node [Token t]]
 * - [Node [Node lst]]
 *
 * @raise Failure if the input string does not conform to any valid production
 * in the original grammar.
 *)
val parse : Token.t array -> Parse_tree.t
